### PR TITLE
Add save/restore support

### PR DESCRIPTION
**Pull request by jbmorley**

### CODE REVIEW

**Comment by welcoMattic** [comment]
Should be nice to merge this feature ;)

**Comment by gradapin** [comment]
It would be really cool to merge this, I would like to trade pokemons with myself (using an emulator on my computer), but I would need to access the saves for that. (I looked for it everywhere but I can't seem to access it with my unjailbroken iPhone.

**Comment by jbmorley** [comment]
This branch doesn't do what you think it does. It does not save to files which can be accessed, simply supports snapshotting into the local database.

**Comment by jbmorley** [comment]
Closing so people don't do drive-by suggestions to merge an incomplete PR.

**Pull request closed without merging**
